### ISSUE TITLE
Mismatched Tag exception.

### ISSUE THREAD

**Issue by jenstroeger** [opentok/Opentok-Python-SDK#148] opened 2019-06-07 06:28 UTC
When calling
```python
_tokbox_sdk = OpenTok(apikey, secret)
tokbox_session = _tokbox_sdk.create_session(media_mode=MediaModes.routed)
```
the framework threw the following exception:
```
Traceback (most recent call last):
  File "/…/lib/python3.7/site-packages/opentok/opentok.py", line 291, in create_session
    dom = xmldom.parseString(response.content)
  File "/usr/lib/python3.7/xml/dom/minidom.py", line 1968, in parseString
    return expatbuilder.parseString(string)
  File "/usr/lib/python3.7/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/lib/python3.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: mismatched tag: line 6, column 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/…/mystuff/utils/tokbox.py", line 86, in create_tokbox_session
    tokbox_session = _create_tokbox_session(dbsession)
  File "/…/mystuff/utils/tokbox.py", line 65, in _create_tokbox_session
    tokbox_session = _tokbox_sdk.create_session(media_mode=MediaModes.routed)
  File "/…/lib/python3.7/site-packages/opentok/opentok.py", line 293, in create_session
    raise RequestError('Failed to create session: %s' % str(e))
opentok.exceptions.RequestError: Failed to create session: mismatched tag: line 6, column 2
```
Looks like the Tokbox server returns a response to the client that the client is unable to handle.

**Comment by jbvsmo** [comment] 2020-04-15 03:58
I've got some high volume of these errors on an unchanged code base yesterday.
I believe it is some server side unavailability error which does not return XML but some more generic message.

Is someone looking into this?

**Comment by msach22** [comment] 2020-04-15 04:10
@jbvsmo We had an issue with our standard api service today which may have been the reason why you were unable to create a session. For more info, please see: https://status.tokbox.com/
The server was returning a 502.

Looks like the SDK is having a parsing issue: https://github.com/opentok/Opentok-Python-SDK/blob/master/opentok/opentok.py#L291

@MichaelJolley Can someone on your team take a look?

**Comment by dragonmantank** [comment] 2020-04-15 13:20
Having @superdiana take a look since it's the Python SDK

**Comment by superdiana** [comment] 2020-04-15 13:44
Taking a look now. Will reproduce and update

**Comment by superdiana** [comment] 2020-04-15 16:59
@msach22 @dragonmantank  @jenstroeger @jbvsmo - indeed a parsing issue. This could be either a special character not being parsed correctly or the fact that `parseString` receives data type string as a parameter and for some reason, the returned data is of type Bytes!.

For future reference, I will include an issue template where I can gather more data like Python & Opentok version as well as environment details. I will push a fix for this.

**Closed** 2020-04-21 00:29 UTC
